name: Go
on:
  push:
    branches:
      - master
      - v3-dev
  pull_request:
    branches: 
      - master
      - v3-dev

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: go test -race -shuffle -failfast -timeout 1m ./...
